/************************************************************************//**
 *     PROJECT: PGPBXToCMake
 *    FILENAME: PBXFileReference.h
 *         IDE: AppCode
 *      AUTHOR: Galen Rhodes
 *        DATE: 2018-11-19
 *
 * Copyright © 2018 Project Galen. All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *//************************************************************************/

#ifndef __PGPBXTOCMAKE_PBXFILEREFERENCE__
#define __PGPBXTOCMAKE_PBXFILEREFERENCE__

#import "PBXFileElement.h"

typedef NS_ENUM(NSUInteger, PBXFileTypeEnum) {
    PBX_FILE_TYPE_NONE = 0,
    PBX_FILE_TYPE_ARCHIVE_AR,
    PBX_FILE_TYPE_ARCHIVE_ASDICTIONARY,
    PBX_FILE_TYPE_ARCHIVE_BINHEX,
    PBX_FILE_TYPE_ARCHIVE_EAR,
    PBX_FILE_TYPE_ARCHIVE_GZIP,
    PBX_FILE_TYPE_ARCHIVE_JAR,
    PBX_FILE_TYPE_ARCHIVE_MACBINARY,
    PBX_FILE_TYPE_ARCHIVE_PPOB,
    PBX_FILE_TYPE_ARCHIVE_RSRC,
    PBX_FILE_TYPE_ARCHIVE_STUFFIT,
    PBX_FILE_TYPE_ARCHIVE_TAR,
    PBX_FILE_TYPE_ARCHIVE_WAR,
    PBX_FILE_TYPE_ARCHIVE_ZIP,
    PBX_FILE_TYPE_AUDIO_AIFF,
    PBX_FILE_TYPE_AUDIO_AU,
    PBX_FILE_TYPE_AUDIO_MIDI,
    PBX_FILE_TYPE_AUDIO_MP3,
    PBX_FILE_TYPE_AUDIO_WAV,
    PBX_FILE_TYPE_COMPILED_MACHO,
    PBX_FILE_TYPE_COMPILED_MACHO_BUNDLE,
    PBX_FILE_TYPE_COMPILED_MACHO_COREFILE,
    PBX_FILE_TYPE_COMPILED_MACHO_DYLIB,
    PBX_FILE_TYPE_COMPILED_MACHO_FVMLIB,
    PBX_FILE_TYPE_COMPILED_MACHO_OBJFILE,
    PBX_FILE_TYPE_COMPILED_MACHO_PRELOAD,
    PBX_FILE_TYPE_FILE_BPLIST,
    PBX_FILE_TYPE_FILE_XIB,
    PBX_FILE_TYPE_IMAGE_BMP,
    PBX_FILE_TYPE_IMAGE_GIF,
    PBX_FILE_TYPE_IMAGE_ICNS,
    PBX_FILE_TYPE_IMAGE_ICO,
    PBX_FILE_TYPE_IMAGE_JPEG,
    PBX_FILE_TYPE_IMAGE_PDF,
    PBX_FILE_TYPE_IMAGE_PICT,
    PBX_FILE_TYPE_IMAGE_PNG,
    PBX_FILE_TYPE_IMAGE_TIFF,
    PBX_FILE_TYPE_PATTERN_PROXY,
    PBX_FILE_TYPE_SOURCECODE_ADA,
    PBX_FILE_TYPE_SOURCECODE_APPLESCRIPT,
    PBX_FILE_TYPE_SOURCECODE_ASM,
    PBX_FILE_TYPE_SOURCECODE_ASM_ASM,
    PBX_FILE_TYPE_SOURCECODE_ASM_LLVM,
    PBX_FILE_TYPE_SOURCECODE_C,
    PBX_FILE_TYPE_SOURCECODE_C_C_PREPROCESSED,
    PBX_FILE_TYPE_SOURCECODE_C_H,
    PBX_FILE_TYPE_SOURCECODE_C_OBJC,
    PBX_FILE_TYPE_SOURCECODE_C_OBJC_PREPROCESSED,
    PBX_FILE_TYPE_SOURCECODE_CPP_CPP,
    PBX_FILE_TYPE_SOURCECODE_CPP_CPP_PREPROCESSED,
    PBX_FILE_TYPE_SOURCECODE_CPP_H,
    PBX_FILE_TYPE_SOURCECODE_CPP_OBJCPP,
    PBX_FILE_TYPE_SOURCECODE_CPP_OBJCPP_PREPROCESSED,
    PBX_FILE_TYPE_SOURCECODE_DTRACE,
    PBX_FILE_TYPE_SOURCECODE_EXPORTS,
    PBX_FILE_TYPE_SOURCECODE_FORTRAN,
    PBX_FILE_TYPE_SOURCECODE_FORTRAN_F77,
    PBX_FILE_TYPE_SOURCECODE_FORTRAN_F90,
    PBX_FILE_TYPE_SOURCECODE_GLSL,
    PBX_FILE_TYPE_SOURCECODE_JAM,
    PBX_FILE_TYPE_SOURCECODE_JAVA,
    PBX_FILE_TYPE_SOURCECODE_JAVASCRIPT,
    PBX_FILE_TYPE_SOURCECODE_LEX,
    PBX_FILE_TYPE_SOURCECODE_MAKE,
    PBX_FILE_TYPE_SOURCECODE_MIG,
    PBX_FILE_TYPE_SOURCECODE_NASM,
    PBX_FILE_TYPE_SOURCECODE_OPENCL,
    PBX_FILE_TYPE_SOURCECODE_PASCAL,
    PBX_FILE_TYPE_SOURCECODE_REZ,
    PBX_FILE_TYPE_SOURCECODE_YACC,
    PBX_FILE_TYPE_TEXT,
    PBX_FILE_TYPE_TEXT_CSS,
    PBX_FILE_TYPE_TEXT_HTML_DOCUMENTATION,
    PBX_FILE_TYPE_TEXT_MAN,
    PBX_FILE_TYPE_TEXT_PBXPROJECT,
    PBX_FILE_TYPE_TEXT_PLIST,
    PBX_FILE_TYPE_TEXT_PLIST_INFO,
    PBX_FILE_TYPE_TEXT_PLIST_SCRIPTSUITE,
    PBX_FILE_TYPE_TEXT_PLIST_SCRIPTTERMINOLOGY,
    PBX_FILE_TYPE_TEXT_PLIST_STRINGS,
    PBX_FILE_TYPE_TEXT_PLIST_XCLANGSPEC,
    PBX_FILE_TYPE_TEXT_PLIST_XCSYNSPEC,
    PBX_FILE_TYPE_TEXT_PLIST_XCTXTMACRO,
    PBX_FILE_TYPE_TEXT_PLIST_XML,
    PBX_FILE_TYPE_TEXT_RTF,
    PBX_FILE_TYPE_TEXT_SCRIPT,
    PBX_FILE_TYPE_TEXT_SCRIPT_CSH,
    PBX_FILE_TYPE_TEXT_SCRIPT_PERL,
    PBX_FILE_TYPE_TEXT_SCRIPT_PHP,
    PBX_FILE_TYPE_TEXT_SCRIPT_PYTHON,
    PBX_FILE_TYPE_TEXTSCRIPT_RUBY,
    PBX_FILE_TYPE_TEXT_SCRIPTSH,
    PBX_FILE_TYPE_TEXT_SCRIPT_WORKSHEET,
    PBX_FILE_TYPE_TEXT_XCCONFIG,
    PBX_FILE_TYPE_TEXT_XML,
    PBX_FILE_TYPE_VIDEO_AVI,
    PBX_FILE_TYPE_VIDEO_MPEG,
    PBX_FILE_TYPE_VIDEO_QUARTZCOMPOSER,
    PBX_FILE_TYPE_VIDEO_QUICKTIME,
    PBX_FILE_TYPE_WRAPPER_APPLICATION,
    PBX_FILE_TYPE_WRAPPER_CFBUNDLE,
    PBX_FILE_TYPE_WRAPPER_FRAMEWORK,
    PBX_FILE_TYPE_WRAPPER_PBPROJECT,
    PBX_FILE_TYPE_SOURCECODE_TEXTBASED_DYLIB_DEFINITION
};

typedef NS_ENUM(uint64_t, PBXFileEncodingEnum) {
    PBX_FILE_ENCODING_DEFAULT            = 0,
    PBX_FILE_ENCODING_UTF8               = 4,
    PBX_FILE_ENCODING_UTF16              = 10,
    PBX_FILE_ENCODING_UTF16_BE           = 2415919360,
    PBX_FILE_ENCODING_UTF16_LE           = 2483028224,
    PBX_FILE_ENCODING_WESTERN            = 30,
    PBX_FILE_ENCODING_JAPANESE           = 2147483649,
    PBX_FILE_ENCODING_TRADITIONALCHINESE = 2147483650,
    PBX_FILE_ENCODING_KOREAN             = 2147483651,
    PBX_FILE_ENCODING_ARABIC             = 2147483652,
    PBX_FILE_ENCODING_HEBREW             = 2147483653,
    PBX_FILE_ENCODING_GREEK              = 2147483654,
    PBX_FILE_ENCODING_CYRILLIC           = 2147483655,
    PBX_FILE_ENCODING_SIMPLIFIEDCHINESE  = 2147483673,
    PBX_FILE_ENCODING_CENTRALEUROPEAN    = 2147483677,
    PBX_FILE_ENCODING_TURKISH            = 2147483683,
    PBX_FILE_ENCODING_ICELANDIC          = 2147483685,
};

NS_ASSUME_NONNULL_BEGIN

@interface PBXFileReference : PBXFileElement

    @property(readonly) PBXFileEncodingEnum fileEncoding;
    @property(readonly) NSString            *fileEncodingDescription;
    @property(readonly) NSString            *lastKnownFileTypeDescription;
    @property(readonly) PBXFileTypeEnum     lastKnownFileType;
    @property(readonly) NSString            *explicitFileTypeDescription;
    @property(readonly) PBXFileTypeEnum     explicitFileType;
    @property(readonly) NSString            *path;
    @property(readonly) BOOL                includeInIndex;

    -(instancetype)initWithID:(NSString *)pbxID plist:(PBXDict)plist;

@end

NS_ASSUME_NONNULL_END

#endif // __PGPBXTOCMAKE_PBXFILEREFERENCE__
